import { Paint, Brand, PaintType, PaintSystem } from './types';

// This data is copied from paints.json.
// The string values for brand, type, and paintSystem are compatible with the enums in types.ts.
export const initialPaints: Paint[] = [
  { brand: Brand.CREOS, series: "Mr.カラー", name: "ホワイト", code: "C1", hex: "#ffffff", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "gloss", amazonUrl: "https://www.amazon.co.jp/dp/B0006N71E8" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "ブラック", code: "C2", hex: "#1a1a1a", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "gloss", amazonUrl: "https://www.amazon.co.jp/dp/B0006N71EO" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "レッド", code: "C3", hex: "#c40d2d", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "イエロー", code: "C4", hex: "#fcdb01", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "ブルー", code: "C5", hex: "#004e97", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "グリーン", code: "C6", hex: "#00885a", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "ブラウン", code: "C7", hex: "#8a4e3a", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "シルバー", code: "C8", hex: "#c0c0c0", type: PaintType.METALLIC, paintSystem: PaintSystem.LACQUER, finish: "gloss", amazonUrl: "https://www.amazon.co.jp/dp/B0006N71F2" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "ゴールド", code: "C9", hex: "#d4af37", type: PaintType.METALLIC, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "カッパー", code: "C10", hex: "#b87333", type: PaintType.METALLIC, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "ガルグレー", code: "C11", hex: "#a9adaf", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "semi-gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "オリーブドラブ(1)", code: "C12", hex: "#5b5435", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "semi-gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "ニュートラルグレー", code: "C13", hex: "#7d7d7d", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "ネービーブルー", code: "C14", hex: "#323f4a", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "暗緑色（中島系）", code: "C15", hex: "#3e4730", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "semi-gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "緑", code: "C16", hex: "#2c6a4a", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "ダークグリーン(2)", code: "C17", hex: "#425448", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "semi-gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "RLM70 ブラックグリーン", code: "C18", hex: "#333d36", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "semi-gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "サンディブラウン", code: "C19", hex: "#b8906b", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "semi-gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "ライトブルー", code: "C20", hex: "#6c93b1", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "semi-gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "ミドルストーン", code: "C21", hex: "#a4815a", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "semi-gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "ダークアース", code: "C22", hex: "#7a6a53", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "semi-gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "ダークグリーン(1)", code: "C23", hex: "#474a43", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "semi-gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "スカイ", code: "C24", hex: "#a8b5a0", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "semi-gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "ダークシーグレー", code: "C25", hex: "#8c9497", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "semi-gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "ダックエッググリーン", code: "C26", hex: "#c6d1c0", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "semi-gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "機体内部色", code: "C27", hex: "#99ab83", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "semi-gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "黒鉄色", code: "C28", hex: "#3d4045", type: PaintType.METALLIC, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "艦底色", code: "C29", hex: "#8a4e3a", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "semi-gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "クリアー", code: "C30", hex: "#ffffff", type: PaintType.CLEAR, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "軍艦色(1)", code: "C31", hex: "#595e62", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "semi-gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "軍艦色(2)", code: "C32", hex: "#737572", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "semi-gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "つや消しブラック", code: "C33", hex: "#2a2a2a", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "matte" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "スカイブルー", code: "C34", hex: "#83c3dc", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "明灰白色(1)", code: "C35", hex: "#c7c6c0", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "semi-gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "RLM74 グレーグリーン", code: "C36", hex: "#4d5144", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "semi-gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "RLM75 グレーバイオレット", code: "C37", hex: "#7b7e80", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "semi-gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "オリーブドラブ(2)", code: "C38", hex: "#6a603d", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "semi-gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "ダークイエロー", code: "C39", hex: "#b48c52", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "semi-gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "ジャーマングレー", code: "C40", hex: "#525558", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "semi-gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "レッドブラウン", code: "C41", hex: "#8e5243", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "マホガニー", code: "C42", hex: "#6b3f31", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "ウッドブラウン", code: "C43", hex: "#946c45", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "タン", code: "C44", hex: "#c9a16f", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "セールカラー", code: "C45", hex: "#ece3c7", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "クリアー", code: "C46", hex: "#ffffff", type: PaintType.CLEAR, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "クリアーレッド", code: "C47", hex: "#e5002d", type: PaintType.CLEAR, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "クリアーイエロー", code: "C48", hex: "#ffd900", type: PaintType.CLEAR, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "クリアーオレンジ", code: "C49", hex: "#f58220", type: PaintType.CLEAR, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "クリアーブルー", code: "C50", hex: "#005ecb", type: PaintType.CLEAR, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "肌色", code: "C51", hex: "#fcd4b4", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "semi-gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "フィールドグレー(1)", code: "C52", hex: "#6b6955", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "semi-gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "フィールドグレー(2)", code: "C53", hex: "#8a8977", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "semi-gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "カーキグリーン", code: "C54", hex: "#9b925b", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "semi-gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "カーキ", code: "C55", hex: "#b4a97f", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "semi-gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "明緑色", code: "C56", hex: "#a4b09b", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "semi-gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "メタリックグリーン", code: "C57", hex: "#5d8478", type: PaintType.METALLIC, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "黄橙色", code: "C58", hex: "#f8a228", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "オレンジ", code: "C59", hex: "#f37821", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "オレンジイエロー", code: "C60", hex: "#f9bc1b", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "焼鉄色", code: "C61", hex: "#4d413a", type: PaintType.METALLIC, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "つや消しホワイト", code: "C62", hex: "#f0f0f0", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "matte" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "ピンク", code: "C63", hex: "#f0a2b6", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "RLM04 イエロー", code: "C64", hex: "#f7b731", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "インディブルー", code: "C65", hex: "#007ec5", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "RLM71 ダークグリーン", code: "C66", hex: "#4a4f3a", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "semi-gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "パープル", code: "C67", hex: "#8f4d9d", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "モンザレッド", code: "C68", hex: "#d8242a", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "RLM78 ライトブルー", code: "C69", hex: "#7b90a3", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "semi-gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "RLM80 オリーブグリーン", code: "C70", hex: "#6e6a39", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "semi-gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "ミッドナイトブルー", code: "C71", hex: "#222c3c", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "ダークグリーン", code: "C72", hex: "#3b483e", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "エアクラフトグレー", code: "C73", hex: "#a4a8aa", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "オリーブグリーン", code: "C74", hex: "#6c6a48", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "ダークシーグレー", code: "C75", hex: "#5a6468", type: PaintType.METALLIC, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "コバルトブルー", code: "C76", hex: "#0047ab", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "メタリックブルー", code: "C77", hex: "#4b6f95", type: PaintType.METALLIC, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "メタリックレッド", code: "C78", hex: "#a63d41", type: PaintType.METALLIC, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "シャインレッド", code: "C79", hex: "#e60012", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "デイトナグリーン", code: "C80", hex: "#00876a", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "蛍光レッド", code: "C87", hex: "#ff3a21", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "蛍光グリーン", code: "C88", hex: "#00ff7f", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "蛍光イエロー", code: "C89", hex: "#ffff00", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "蛍光ピンク", code: "C90", hex: "#ff69b4", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "蛍光オレンジ", code: "C91", hex: "#ffa500", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "スモークグレー", code: "C92", hex: "#808080", type: PaintType.CLEAR, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "クリアーオレンジ", code: "C93", hex: "#f58220", type: PaintType.CLEAR, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "クリアーグリーン", code: "C94", hex: "#009e49", type: PaintType.CLEAR, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "クリアーブラウン", code: "C101", hex: "#8c592a", type: PaintType.CLEAR, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "G-キャラクターホワイト", code: "C107", hex: "#f2f2f2", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "G-キャラクターレッド", code: "C108", hex: "#e63644", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "G-キャラクターイエロー", code: "C109", hex: "#f6b42c", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "G-キャラクターブルー", code: "C110", hex: "#2c8fde", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "G-キャラクターフレッシュ(1)", code: "C111", hex: "#f8d3c1", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "G-キャラクターフレッシュ(2)", code: "C112", hex: "#f8c6b1", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "RLM65 ライトブルー", code: "C115", hex: "#8fb1bc", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "semi-gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "RLM76 ライトブルー", code: "C117", hex: "#c0cdd1", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "semi-gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "RLM79 サンディイエロー", code: "C119", hex: "#a4815a", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "semi-gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "RLM81 ブラウンバイオレット", code: "C120", hex: "#6a5c4d", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "semi-gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "RLM82 ライトグリーン", code: "C121", hex: "#7a8459", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "semi-gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "RLM83 ダークグリーン", code: "C122", hex: "#474a3a", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "semi-gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "コクピット色(三菱系)", code: "C124", hex: "#5a664f", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "semi-gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "カウリング色", code: "C125", hex: "#2e343b", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "semi-gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "コクピット色(中島系)", code: "C126", hex: "#4a594b", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "semi-gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "機体内部色", code: "C127", hex: "#9d9b7c", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "semi-gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "灰色(三菱系)", code: "C128", hex: "#bfb8a6", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "semi-gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "濃緑色(三菱系)", code: "C129", hex: "#3a443a", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "semi-gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "濃緑色(中島系)", code: "C130", hex: "#41483f", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "semi-gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "あずき色", code: "C131", hex: "#8e4a4d", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "semi-gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "ダークグリーンWWII", code: "C132", hex: "#575d4e", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "semi-gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "赤褐色", code: "C136", hex: "#b05749", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "matte" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "タイヤブラック", code: "C137", hex: "#3f3f3f", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "matte" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "フラットベース(なめらか)", code: "C189", hex: "#ffffff", type: PaintType.CLEAR, paintSystem: PaintSystem.LACQUER, finish: "matte" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "オリーブドラブFS34087", code: "C304", hex: "#5a5647", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "semi-gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "グレーFS36118", code: "C305", hex: "#5b6063", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "semi-gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "グレーFS36231", code: "C306", hex: "#7a8286", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "semi-gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "グレーFS36320", code: "C307", hex: "#9da3a6", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "semi-gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "グレーFS36375", code: "C308", hex: "#c5c8c9", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "semi-gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "ダークシーグレー", code: "C331", hex: "#4f5a60", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "semi-gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "エクストラダークシーグレー", code: "C333", hex: "#5f6870", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "semi-gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "ミディアムシーグレー", code: "C335", hex: "#939ba0", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "semi-gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "ライトエアクラフトグレー", code: "C337", hex: "#c5c9c8", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "semi-gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "ダックエッググリーン", code: "C364", hex: "#adc2a9", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "semi-gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "RLM76 ライトブルー", code: "C368", hex: "#c0cdd1", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "semi-gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "ダークイエロー", code: "C512", hex: "#a98d54", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "semi-gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "ブラックグレー", code: "C513", hex: "#414342", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "semi-gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "ジャーマングレー(ドゥンケルグラウ)", code: "C514", hex: "#4b4f53", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "semi-gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "タン（ロシア）", code: "C517", hex: "#c3a985", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "semi-gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "ロシアングreen（１）", code: "C518", hex: "#5c604f", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "semi-gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "ブルー（ロシア）", code: "C519", hex: "#748ca0", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "semi-gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "RLM79 サンディブラウン", code: "C524", hex: "#9a7c55", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "semi-gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "ウイノーブラック", code: "C181", hex: "#1c1c1c", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "semi-gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "スーパークリアー つや消し", code: "C182", hex: "#ffffff", type: PaintType.CLEAR, paintSystem: PaintSystem.LACQUER, finish: "matte" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "スーパークリアー 光沢", code: "C184", hex: "#ffffff", type: PaintType.CLEAR, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "スーパークリアー 半光沢", code: "C188", hex: "#ffffff", type: PaintType.CLEAR, paintSystem: PaintSystem.LACQUER, finish: "semi-gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "フラットベース", code: "C189", hex: "#ffffff", type: PaintType.CLEAR, paintSystem: PaintSystem.LACQUER, finish: "matte" },
  { brand: Brand.CREOS, series: "Mr.カラーGX", name: "クールホワイト", code: "GX1", hex: "#f8f8f8", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "Mr.カラーGX", name: "ウィノーブラック", code: "GX2", hex: "#101010", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "Mr.カラーGX", name: "ハーマンレッド", code: "GX3", hex: "#c82c24", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "Mr.カラーGX", name: "キアライエロー", code: "GX4", hex: "#fcc800", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "Mr.カラーGX", name: "スージーブルー", code: "GX5", hex: "#0059a3", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "Mr.カラーGX", name: "クリアーブラック", code: "GX101", hex: "#222222", type: PaintType.CLEAR, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "Mr.カラーGX", name: "ディープクリアーレッド", code: "GX102", hex: "#c0002a", type: PaintType.CLEAR, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "Mr.カラーGX", name: "ディープクリアーブルー", code: "GX103", hex: "#004098", type: PaintType.CLEAR, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "Mr.カラーGX", name: "クリアーグリーン", code: "GX104", hex: "#008c4b", type: PaintType.CLEAR, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "Mr.カラーGX", name: "クリアーピンク", code: "GX105", hex: "#ea5da4", type: PaintType.CLEAR, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "Mr.カラーGX", name: "クリアーオレンジ", code: "GX106", hex: "#f37821", type: PaintType.CLEAR, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "Mr.カラーGX", name: "クリアーバイオレット", code: "GX107", hex: "#8f4d9d", type: PaintType.CLEAR, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "Mr.カラーGX", name: "クリアーイエロー", code: "GX108", hex: "#fde300", type: PaintType.CLEAR, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "Mr.カラーGX", name: "スーパークリアーIII UVカット 光沢", code: "GX112", hex: "#ffffff", type: PaintType.CLEAR, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "Mr.カラーGX", name: "スーパークリアーIII UVカット つや消し", code: "GX113", hex: "#ffffff", type: PaintType.CLEAR, paintSystem: PaintSystem.LACQUER, finish: "matte" },
  { brand: Brand.CREOS, series: "Mr.カラーGX", name: "スーパースムースクリアー つや消し", code: "GX114", hex: "#ffffff", type: PaintType.CLEAR, paintSystem: PaintSystem.LACQUER, finish: "matte" },
  { brand: Brand.CREOS, series: "Mr.カラーGX", name: "メタルブラック", code: "GX201", hex: "#2c2c2e", type: PaintType.METALLIC, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "Mr.カラーGX", name: "メタルレッド", code: "GX202", hex: "#b43939", type: PaintType.METALLIC, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "Mr.カラーGX", name: "メタルイエロー", code: "GX204", hex: "#d8a437", type: PaintType.METALLIC, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "Mr.カラーGX", name: "メタルブルー", code: "GX206", hex: "#3c6f96", type: PaintType.METALLIC, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "Mr.カラーGX", name: "メタルバイオレット", code: "GX208", hex: "#8a588b", type: PaintType.METALLIC, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "Mr.カラーGX", name: "メタルピーチ", code: "GX209", hex: "#e8b0a3", type: PaintType.METALLIC, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "Mr.カラーGX", name: "ブルーゴールド", code: "GX210", hex: "#d8c474", type: PaintType.METALLIC, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "Mr.カラーGX", name: "ホワイトシルバー", code: "GX213", hex: "#e0e0e0", type: PaintType.METALLIC, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "Mr.クリスタルカラー", name: "ダイヤモンドシルバー", code: "XC01", hex: "#e0e0e0", type: PaintType.PEARL, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "Mr.クリスタルカラー", name: "トパーズゴールド", code: "XC02", hex: "#e6c88e", type: PaintType.PEARL, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "Mr.クリスタルカラー", name: "ルビーレッド", code: "XC03", hex: "#d94e6c", type: PaintType.PEARL, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "Mr.クリスタルカラー", name: "アメジストパープル", code: "XC04", hex: "#9f74c5", type: PaintType.PEARL, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "Mr.クリスタルカラー", name: "サファイアブルー", code: "XC05", hex: "#6998cb", type: PaintType.PEARL, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "Mr.クリスタルカラー", name: "トルマリングリーン", code: "XC06", hex: "#67b4a3", type: PaintType.PEARL, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "Mr.クリスタルカラー", name: "ディープクリアーレッド", code: "XC07", hex: "#c0002a", type: PaintType.CLEAR, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "Mr.クリスタルカラー", name: "ディープクリアーブルー", code: "XC08", hex: "#004098", type: PaintType.CLEAR, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "Mr.メタルカラー", name: "クロームシルバー", code: "MC211", hex: "#d0d0d5", type: PaintType.METALLIC, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "Mr.メタルカラー", name: "アイアン", code: "MC212", hex: "#5a5a5e", type: PaintType.METALLIC, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "Mr.メタルカラー", name: "ステンレス", code: "MC213", hex: "#a8a8aa", type: PaintType.METALLIC, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "Mr.メタルカラー", name: "ダークアイアン", code: "MC214", hex: "#434345", type: PaintType.METALLIC, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "Mr.メタルカラー", name: "アルミ", code: "MC218", hex: "#b4b4b6", type: PaintType.METALLIC, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "スーパーメタリック2", name: "スーパーファインシルバー2", code: "SM201", hex: "#e3e3e3", type: PaintType.METALLIC, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "スーパーメタリック2", name: "スーパーゴールド2", code: "SM202", hex: "#eac146", type: PaintType.METALLIC, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "スーパーメタリック2", name: "スーパーアイアン2", code: "SM203", hex: "#4a4949", type: PaintType.METALLIC, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "スーパーメタリック2", name: "スーパーステンレス2", code: "SM204", hex: "#b8b8b8", type: PaintType.METALLIC, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "スーパーメタリック2", name: "スーパーチタン2", code: "SM205", hex: "#8a8a8a", type: PaintType.METALLIC, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "スーパーメタリック2", name: "スーパークロームシルバー2", code: "SM206", hex: "#f0f0f0", type: PaintType.METALLIC, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー LASCIVUS", name: "白桃(シロモモ)色", code: "CL01", hex: "#fbe5da", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "semi-gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー LASCIVUS", name: "蜜柑(ミカン)色", code: "CL02", hex: "#fdd5c1", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "semi-gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー LASCIVUS", name: "亜麻(アマ)色", code: "CL03", hex: "#efcfb2", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "semi-gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー LASCIVUS", name: "栗色", code: "CL04", hex: "#dca78a", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "semi-gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー LASCIVUS", name: "檜肌(ヒハダ)色", code: "CL05", hex: "#c48868", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "semi-gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー LASCIVUS", name: "ココア色", code: "CL06", hex: "#a6684d", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "semi-gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー LASCIVUS", name: "キャラメル色", code: "CL07", hex: "#874c33", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "semi-gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー LASCIVUS", name: "アプリコット色", code: "CL08", hex: "#7a3b25", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "semi-gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー LASCIVUS", name: "胡桃(クルミ)色パール", code: "CL09", hex: "#f4e0d4", type: PaintType.PEARL, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー LASCIVUS", name: "胡桃(クルミ)色ベルベット", code: "CL10", hex: "#e4c6b5", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "velvet" },
  { brand: Brand.CREOS, series: "Mr.カラー LASCIVUS", name: "スムースパールコート", code: "CL11", hex: "#ffffff", type: PaintType.PEARL, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.GAIA, series: "ガイアカラー", name: "ピュアホワイト", code: "001", hex: "#fefefe", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.GAIA, series: "ガイアカラー", name: "ピュアブラック", code: "002", hex: "#0d0d0d", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.GAIA, series: "ガイアカラー", name: "ブライトレッド", code: "003", hex: "#e60012", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.GAIA, series: "ガイアカラー", name: "ウルトラブルー", code: "004", hex: "#001a83", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.GAIA, series: "ガイアカラー", name: "サンシャインイエロー", code: "005", hex: "#ffd900", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.GAIA, series: "ガイアカラー", name: "純色シアン", code: "025", hex: "#00aeef", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.GAIA, series: "ガイアカラー", name: "純色マゼンタ", code: "026", hex: "#e5007f", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.GAIA, series: "ガイアカラー", name: "ニュートラルグレーI", code: "071", hex: "#e1e1e1", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.GAIA, series: "ガイアカラー", name: "ニュートラルグレーII", code: "072", hex: "#c3c3c3", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.GAIA, series: "ガイアカラー", name: "ニュートラルグレーIII", code: "073", hex: "#9a9a9a", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.GAIA, series: "ガイアカラー", name: "ニュートラルグレーIV", code: "074", hex: "#5f5f5f", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.GAIA, series: "ガイアカラー", name: "ブライトシルバー", code: "009", hex: "#e0e0e0", type: PaintType.METALLIC, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.GAIA, series: "ガイアカラー", name: "ブライトゴールド", code: "010", hex: "#e7b640", type: PaintType.METALLIC, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.GAIA, series: "ガイアカラー", name: "ガンメタル", code: "020", hex: "#444a59", type: PaintType.METALLIC, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.GAIA, series: "ガイアカラー(クリアー)", name: "クリアーレッド", code: "041", hex: "#f2003c", type: PaintType.CLEAR, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.GAIA, series: "ガイアカラー(クリアー)", name: "クリアーブルー", code: "042", hex: "#005aff", type: PaintType.CLEAR, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.GAIA, series: "ガイアカラー(クリアー)", name: "クリアーイエロー", code: "043", hex: "#ffec00", type: PaintType.CLEAR, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.GAIA, series: "ガイアカラー(クリアー)", name: "クリアーグリーン", code: "044", hex: "#00a15d", type: PaintType.CLEAR, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.GAIA, series: "ガイアカラー(クリアー)", name: "クリアーオレンジ", code: "045", hex: "#f7931e", type: PaintType.CLEAR, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.GAIA, series: "ガイアカラー(クリアー)", name: "クリアーパープル", code: "047", hex: "#b853a2", type: PaintType.CLEAR, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.GAIA, series: "ガイアカラー(クリアー)", name: "クリアーブラウン", code: "048", hex: "#9b6e3d", type: PaintType.CLEAR, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.GAIA, series: "ガイアカラー(クリアー)", name: "スモークグレー", code: "046", hex: "#777777", type: PaintType.CLEAR, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.GAIA, series: "ガイアカラー(クリアー)", name: "クリアーホワイト", code: "050", hex: "#ffffff", type: PaintType.CLEAR, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.GAIA, series: "Exシリーズ", name: "Ex-ホワイト", code: "Ex-01", hex: "#ffffff", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.GAIA, series: "Exシリーズ", name: "Ex-ブラック", code: "Ex-02", hex: "#0a0a0a", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.GAIA, series: "Exシリーズ", name: "Ex-クリアー", code: "Ex-03", hex: "#ffffff", type: PaintType.CLEAR, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.GAIA, series: "Exシリーズ", name: "Ex-フラットクリアー", code: "Ex-04", hex: "#ffffff", type: PaintType.CLEAR, paintSystem: PaintSystem.LACQUER, finish: "matte" },
  { brand: Brand.GAIA, series: "Exシリーズ", name: "Ex-シルバー", code: "Ex-07", hex: "#dcdcdc", type: PaintType.METALLIC, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.GAIA, series: "Exシリーズ", name: "Ex-ゴールド", code: "Ex-08", hex: "#e9be44", type: PaintType.METALLIC, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.GAIA, series: "スターブライト", name: "スターブライト シルバー", code: "121", hex: "#d0d0d7", type: PaintType.METALLIC, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.GAIA, series: "スターブライト", name: "スターブライト ゴールド", code: "122", hex: "#e1b433", type: PaintType.METALLIC, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.GAIA, series: "スターブライト", name: "スターブライト ブラス", code: "123", hex: "#c7993a", type: PaintType.METALLIC, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.GAIA, series: "スターブライト", name: "スターブライト ジュラルミン", code: "124", hex: "#a4a4ab", type: PaintType.METALLIC, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.GAIA, series: "スターブライト", name: "スターブライト アイアン", code: "125", hex: "#55555c", type: PaintType.METALLIC, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.GAIA, series: "パールカラー", name: "パール シルバー", code: "131", hex: "#d0d0d7", type: PaintType.PEARL, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.GAIA, series: "パールカラー", name: "パール ゴールド", code: "132", hex: "#e1b433", type: PaintType.PEARL, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.GAIA, series: "パールカラー", name: "パール カッパー", code: "133", hex: "#d99066", type: PaintType.PEARL, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.GAIA, series: "プレミアムシリーズ", name: "プレミアムミラークローム", code: "GP-08", hex: "#f5f5f5", type: PaintType.METALLIC, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "水性ホビーカラー", name: "ホワイト", code: "H1", hex: "#ffffff", type: PaintType.NORMAL, paintSystem: PaintSystem.WATER_BASED, finish: "gloss" },
  { brand: Brand.CREOS, series: "水性ホビーカラー", name: "ブラック", code: "H2", hex: "#1a1a1a", type: PaintType.NORMAL, paintSystem: PaintSystem.WATER_BASED, finish: "gloss" },
  { brand: Brand.CREOS, series: "水性ホビーカラー", name: "レッド", code: "H3", hex: "#c50c2c", type: PaintType.NORMAL, paintSystem: PaintSystem.WATER_BASED, finish: "gloss" },
  { brand: Brand.CREOS, series: "水性ホビーカラー", name: "イエロー", code: "H4", hex: "#fddb00", type: PaintType.NORMAL, paintSystem: PaintSystem.WATER_BASED, finish: "gloss" },
  { brand: Brand.CREOS, series: "水性ホビーカラー", name: "ブルー", code: "H5", hex: "#004d96", type: PaintType.NORMAL, paintSystem: PaintSystem.WATER_BASED, finish: "gloss" },
  { brand: Brand.CREOS, series: "水性ホビーカラー", name: "グリーン", code: "H6", hex: "#008759", type: PaintType.NORMAL, paintSystem: PaintSystem.WATER_BASED, finish: "gloss" },
  { brand: Brand.CREOS, series: "水性ホビーカラー", name: "ブラウン", code: "H7", hex: "#8b4f3a", type: PaintType.NORMAL, paintSystem: PaintSystem.WATER_BASED, finish: "gloss" },
  { brand: Brand.CREOS, series: "水性ホビーカラー", name: "シルバー", code: "H8", hex: "#c1c1c1", type: PaintType.METALLIC, paintSystem: PaintSystem.WATER_BASED, finish: "gloss" },
  { brand: Brand.CREOS, series: "水性ホビーカラー", name: "ゴールド", code: "H9", hex: "#d5af38", type: PaintType.METALLIC, paintSystem: PaintSystem.WATER_BASED, finish: "gloss" },
  { brand: Brand.CREOS, series: "水性ホビーカラー", name: "カッパー", code: "H10", hex: "#b97434", type: PaintType.METALLIC, paintSystem: PaintSystem.WATER_BASED, finish: "gloss" },
  { brand: Brand.CREOS, series: "水性ホビーカラー", name: "つや消しホワイト", code: "H11", hex: "#f0f0f0", type: PaintType.NORMAL, paintSystem: PaintSystem.WATER_BASED, finish: "matte" },
  { brand: Brand.CREOS, series: "水性ホビーカラー", name: "つや消しブラック", code: "H12", hex: "#2b2b2b", type: PaintType.NORMAL, paintSystem: PaintSystem.WATER_BASED, finish: "matte" },
  { brand: Brand.CREOS, series: "水性ホビーカラー", name: "ピンク", code: "H19", hex: "#f1a3b7", type: PaintType.NORMAL, paintSystem: PaintSystem.WATER_BASED, finish: "gloss" },
  { brand: Brand.CREOS, series: "水性ホビーカラー", name: "クリアー", code: "H20", hex: "#ffffff", type: PaintType.CLEAR, paintSystem: PaintSystem.WATER_BASED, finish: "gloss" },
  { brand: Brand.CREOS, series: "水性ホビーカラー", name: "黒鉄色", code: "H76", hex: "#3e4146", type: PaintType.METALLIC, paintSystem: PaintSystem.WATER_BASED, finish: "semi-gloss" },
  { brand: Brand.CREOS, series: "水性ホビーカラー", name: "蛍光レッド", code: "H90", hex: "#ff3b22", type: PaintType.NORMAL, paintSystem: PaintSystem.WATER_BASED, finish: "gloss" },
  { brand: Brand.CREOS, series: "水性ホビーカラー", name: "蛍光イエロー", code: "H91", hex: "#ffff01", type: PaintType.NORMAL, paintSystem: PaintSystem.WATER_BASED, finish: "gloss" },
  { brand: Brand.CREOS, series: "水性ホビーカラー", name: "蛍光オレンジ", code: "H92", hex: "#ffa601", type: PaintType.NORMAL, paintSystem: PaintSystem.WATER_BASED, finish: "gloss" },
  { brand: Brand.CREOS, series: "水性ホビーカラー", name: "蛍光グリーン", code: "H94", hex: "#01ff80", type: PaintType.NORMAL, paintSystem: PaintSystem.WATER_BASED, finish: "gloss" },
  { brand: Brand.CREOS, series: "水性ホビーカラー", name: "蛍光ピンク", code: "H98", hex: "#ff6ab5", type: PaintType.NORMAL, paintSystem: PaintSystem.WATER_BASED, finish: "gloss" },
  { brand: Brand.CREOS, series: "水性ホビーカラー スーパーメタリック", name: "スーパーファインシルバー", code: "HSM01", hex: "#e4e4e4", type: PaintType.METALLIC, paintSystem: PaintSystem.WATER_BASED, finish: "gloss" },
  { brand: Brand.CREOS, series: "水性ホビーカラー スーパーメタリック", name: "スーパーゴールド", code: "HSM02", hex: "#ebd247", type: PaintType.METALLIC, paintSystem: PaintSystem.WATER_BASED, finish: "gloss" },
  { brand: Brand.CREOS, series: "水性ホビーカラー スーパーメタリック", name: "スーパーアイアン", code: "HSM03", hex: "#4b4a4a", type: PaintType.METALLIC, paintSystem: PaintSystem.WATER_BASED, finish: "gloss" },
  { brand: Brand.CREOS, series: "水性ガンダムSEEDカラー", name: "ストライクガンダムホワイト", code: "HUG101", hex: "#e8e8e8", type: PaintType.NORMAL, paintSystem: PaintSystem.WATER_BASED, finish: "semi-gloss" },
  { brand: Brand.CREOS, series: "水性ガンダムSEEDカラー", name: "ストライクガンダムレッド", code: "HUG102", hex: "#d34142", type: PaintType.NORMAL, paintSystem: PaintSystem.WATER_BASED, finish: "semi-gloss" },
  { brand: Brand.CREOS, series: "水性ガンダムSEEDカラー", name: "ストライクガンダムブルー", code: "HUG103", hex: "#3c67a3", type: PaintType.NORMAL, paintSystem: PaintSystem.WATER_BASED, finish: "semi-gloss" },
  { brand: Brand.CREOS, series: "水性ガンダムカラー 水星の魔女", name: "ガンダムエアリアル ホワイト", code: "SUISEI-WM01", hex: "#ffffff", type: PaintType.NORMAL, paintSystem: PaintSystem.WATER_BASED, finish: "semi-gloss" },
  { brand: Brand.CREOS, series: "水性ガンダムカラー 水星の魔女", name: "ガンダムエアリアル ブルー", code: "SUISEI-WM02", hex: "#305da6", type: PaintType.NORMAL, paintSystem: PaintSystem.WATER_BASED, finish: "semi-gloss" },
  { brand: Brand.CREOS, series: "水性ガンダムSEED FREEDOMカラー", name: "ライジングフリーダムブルー", code: "FREEDOM-01", hex: "#275a9a", type: PaintType.NORMAL, paintSystem: PaintSystem.WATER_BASED, finish: "semi-gloss" },
  { brand: Brand.CREOS, series: "水性ガンダムSEED FREEDOMカラー", name: "イモータルジャスティスレッド", code: "FREEDOM-02", hex: "#e04e54", type: PaintType.NORMAL, paintSystem: PaintSystem.WATER_BASED, finish: "semi-gloss" },
  { brand: Brand.CREOS, series: "ガンダム アッセンブルモデルカラー", name: "ウェポンズグレー", code: "GAC01", hex: "#66696c", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "semi-gloss" },
  { brand: Brand.CREOS, series: "ガンダム アッセンブルモデルカラー", name: "インナーフレームグレー", code: "GAC02", hex: "#4f555a", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "semi-gloss" },
  { brand: Brand.CREOS, series: "アクリジョン", name: "ホワイト", code: "N1", hex: "#fdfdfd", type: PaintType.NORMAL, paintSystem: PaintSystem.ACRYSION, finish: "gloss" },
  { brand: Brand.CREOS, series: "アクリジョン", name: "ブラック", code: "N2", hex: "#1b1b1b", type: PaintType.NORMAL, paintSystem: PaintSystem.ACRYSION, finish: "gloss" },
  { brand: Brand.CREOS, series: "アクリジョン", name: "レッド", code: "N3", hex: "#d00c2a", type: PaintType.NORMAL, paintSystem: PaintSystem.ACRYSION, finish: "gloss" },
  { brand: Brand.CREOS, series: "アクリジョン", name: "イエロー", code: "N4", hex: "#fedd00", type: PaintType.NORMAL, paintSystem: PaintSystem.ACRYSION, finish: "gloss" },
  { brand: Brand.CREOS, series: "アクリジョン", name: "ブルー", code: "N5", hex: "#004b95", type: PaintType.NORMAL, paintSystem: PaintSystem.ACRYSION, finish: "gloss" },
  { brand: Brand.CREOS, series: "アクリジョン", name: "グリーン", code: "N6", hex: "#008658", type: PaintType.NORMAL, paintSystem: PaintSystem.ACRYSION, finish: "gloss" },
  { brand: Brand.CREOS, series: "アクリジョン", name: "ブラウン", code: "N7", hex: "#8c4e3b", type: PaintType.NORMAL, paintSystem: PaintSystem.ACRYSION, finish: "gloss" },
  { brand: Brand.CREOS, series: "アクリジョン", name: "シルバー", code: "N8", hex: "#c2c2c2", type: PaintType.METALLIC, paintSystem: PaintSystem.ACRYSION, finish: "gloss" },
  { brand: Brand.CREOS, series: "アクリジョン", name: "ゴールド", code: "N9", hex: "#d6b039", type: PaintType.METALLIC, paintSystem: PaintSystem.ACRYSION, finish: "gloss" },
  { brand: Brand.CREOS, series: "アクリジョン", name: "カッパー", code: "N10", hex: "#ba7535", type: PaintType.METALLIC, paintSystem: PaintSystem.ACRYSION, finish: "gloss" },
  { brand: Brand.CREOS, series: "アクリジョン", name: "つや消しホワイト", code: "N11", hex: "#f1f1f1", type: PaintType.NORMAL, paintSystem: PaintSystem.ACRYSION, finish: "matte" },
  { brand: Brand.CREOS, series: "アクリジョン", name: "つや消しブラック", code: "N12", hex: "#2c2c2c", type: PaintType.NORMAL, paintSystem: PaintSystem.ACRYSION, finish: "matte" },
  { brand: Brand.CREOS, series: "アクリジョン", name: "ニュートラルグレー", code: "N13", hex: "#7e7e7e", type: PaintType.NORMAL, paintSystem: PaintSystem.ACRYSION, finish: "gloss" },
  { brand: Brand.CREOS, series: "アクリジョン", name: "ネービーブルー", code: "N14", hex: "#33404b", type: PaintType.NORMAL, paintSystem: PaintSystem.ACRYSION, finish: "gloss" },
  { brand: Brand.CREOS, series: "アクリジョン", name: "暗緑色(中島系)", code: "N15", hex: "#3f4831", type: PaintType.NORMAL, paintSystem: PaintSystem.ACRYSION, finish: "semi-gloss" },
  { brand: Brand.CREOS, series: "アクリジョン", name: "クリアー", code: "N20", hex: "#ffffff", type: PaintType.CLEAR, paintSystem: PaintSystem.ACRYSION, finish: "gloss" },
  { brand: Brand.CREOS, series: "アクリジョン", name: "黒鉄色", code: "N28", hex: "#3e4146", type: PaintType.METALLIC, paintSystem: PaintSystem.ACRYSION, finish: "gloss" },
  { brand: Brand.CREOS, series: "アクリジョン", name: "艦底色", code: "N29", hex: "#8b4f3b", type: PaintType.NORMAL, paintSystem: PaintSystem.ACRYSION, finish: "semi-gloss" },
  { brand: Brand.CREOS, series: "アクリジョン", name: "クリアーレッド", code: "N90", hex: "#e6012e", type: PaintType.CLEAR, paintSystem: PaintSystem.ACRYSION, finish: "gloss" },
  { brand: Brand.CREOS, series: "アクリジョン", name: "クリアーイエロー", code: "N91", hex: "#ffda01", type: PaintType.CLEAR, paintSystem: PaintSystem.ACRYSION, finish: "gloss" },
  { brand: Brand.CREOS, series: "アクリジョン", name: "クリアーブルー", code: "N92", hex: "#015fcc", type: PaintType.CLEAR, paintSystem: PaintSystem.ACRYSION, finish: "gloss" },
  { brand: Brand.CREOS, series: "アクリジョン", name: "クリアーグリーン", code: "N93", hex: "#019f4a", type: PaintType.CLEAR, paintSystem: PaintSystem.ACRYSION, finish: "gloss" },
  { brand: Brand.CREOS, series: "アクリジョン", name: "クリアーオレンジ", code: "N94", hex: "#f68321", type: PaintType.CLEAR, paintSystem: PaintSystem.ACRYSION, finish: "gloss" },
  { brand: Brand.CREOS, series: "アクリジョン ベースカラー", name: "ベースホワイト", code: "BN01", hex: "#f5f5f5", type: PaintType.NORMAL, paintSystem: PaintSystem.ACRYSION, finish: "matte" },
  { brand: Brand.CREOS, series: "アクリジョン ベースカラー", name: "ベースグレー", code: "BN02", hex: "#8a8a8a", type: PaintType.NORMAL, paintSystem: PaintSystem.ACRYSION, finish: "matte" },
  { brand: Brand.CREOS, series: "アクリジョン ベースカラー", name: "ベースイエロー", code: "BN03", hex: "#fde500", type: PaintType.NORMAL, paintSystem: PaintSystem.ACRYSION, finish: "matte" },
  { brand: Brand.CREOS, series: "アクリジョン ベースカラー", name: "ベースレッド", code: "BN04", hex: "#e8382f", type: PaintType.NORMAL, paintSystem: PaintSystem.ACRYSION, finish: "matte" }
];