import { Paint, Brand, PaintType, PaintSystem } from '../../../types';

export const mrColorPaints: Paint[] = [
  { brand: Brand.CREOS, series: "Mr.カラー", name: "ホワイト", code: "C1", hex: "#ffffff", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "gloss", amazonUrl: "https://www.amazon.co.jp/dp/B0006N71E8" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "ブラック", code: "C2", hex: "#1a1a1a", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "gloss", amazonUrl: "https://www.amazon.co.jp/dp/B0006N71EO" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "レッド", code: "C3", hex: "#c40d2d", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "イエロー", code: "C4", hex: "#fcdb01", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "ブルー", code: "C5", hex: "#004e97", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "グリーン", code: "C6", hex: "#00885a", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "ブラウン", code: "C7", hex: "#8a4e3a", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "シルバー", code: "C8", hex: "#c0c0c0", type: PaintType.METALLIC, paintSystem: PaintSystem.LACQUER, finish: "gloss", amazonUrl: "https://www.amazon.co.jp/dp/B0006N71F2" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "ゴールド", code: "C9", hex: "#d4af37", type: PaintType.METALLIC, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "カッパー", code: "C10", hex: "#b87333", type: PaintType.METALLIC, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "ガルグレー", code: "C11", hex: "#a9adaf", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "semi-gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "オリーブドラブ(1)", code: "C12", hex: "#5b5435", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "semi-gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "ニュートラルグレー", code: "C13", hex: "#7d7d7d", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "ネービーブルー", code: "C14", hex: "#323f4a", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "暗緑色（中島系）", code: "C15", hex: "#3e4730", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "semi-gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "緑", code: "C16", hex: "#2c6a4a", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "ダークグリーン(2)", code: "C17", hex: "#425448", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "semi-gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "RLM70 ブラックグリーン", code: "C18", hex: "#333d36", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "semi-gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "サンディブラウン", code: "C19", hex: "#b8906b", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "semi-gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "ライトブルー", code: "C20", hex: "#6c93b1", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "semi-gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "ミドルストーン", code: "C21", hex: "#a4815a", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "semi-gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "ダークアース", code: "C22", hex: "#7a6a53", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "semi-gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "ダークグリーン(1)", code: "C23", hex: "#474a43", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "semi-gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "スカイ", code: "C24", hex: "#a8b5a0", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "semi-gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "ダークシーグレー", code: "C25", hex: "#8c9497", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "semi-gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "ダックエッググリーン", code: "C26", hex: "#c6d1c0", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "semi-gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "機体内部色", code: "C27", hex: "#99ab83", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "semi-gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "黒鉄色", code: "C28", hex: "#3d4045", type: PaintType.METALLIC, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "艦底色", code: "C29", hex: "#8a4e3a", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "semi-gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "クリアー", code: "C30", hex: "#ffffff", type: PaintType.CLEAR, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "軍艦色(1)", code: "C31", hex: "#595e62", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "semi-gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "軍艦色(2)", code: "C32", hex: "#737572", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "semi-gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "つや消しブラック", code: "C33", hex: "#2a2a2a", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "matte" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "スカイブルー", code: "C34", hex: "#83c3dc", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "明灰白色(1)", code: "C35", hex: "#c7c6c0", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "semi-gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "RLM74 グレーグリーン", code: "C36", hex: "#4d5144", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "semi-gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "RLM75 グレーバイオレット", code: "C37", hex: "#7b7e80", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "semi-gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "オリーブドラブ(2)", code: "C38", hex: "#6a603d", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "semi-gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "ダークイエロー", code: "C39", hex: "#b48c52", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "semi-gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "ジャーマングレー", code: "C40", hex: "#525558", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "semi-gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "レッドブラウン", code: "C41", hex: "#8e5243", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "マホガニー", code: "C42", hex: "#6b3f31", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "ウッドブラウン", code: "C43", hex: "#946c45", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "タン", code: "C44", hex: "#c9a16f", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "セールカラー", code: "C45", hex: "#ece3c7", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "クリアー", code: "C46", hex: "#ffffff", type: PaintType.CLEAR, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "クリアーレッド", code: "C47", hex: "#e5002d", type: PaintType.CLEAR, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "クリアーイエロー", code: "C48", hex: "#ffd900", type: PaintType.CLEAR, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "クリアーオレンジ", code: "C49", hex: "#f58220", type: PaintType.CLEAR, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "クリアーブルー", code: "C50", hex: "#005ecb", type: PaintType.CLEAR, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "肌色", code: "C51", hex: "#fcd4b4", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "semi-gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "フィールドグレー(1)", code: "C52", hex: "#6b6955", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "semi-gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "フィールドグレー(2)", code: "C53", hex: "#8a8977", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "semi-gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "カーキグリーン", code: "C54", hex: "#9b925b", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "semi-gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "カーキ", code: "C55", hex: "#b4a97f", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "semi-gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "明緑色", code: "C56", hex: "#a4b09b", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "semi-gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "メタリックグリーン", code: "C57", hex: "#5d8478", type: PaintType.METALLIC, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "黄橙色", code: "C58", hex: "#f8a228", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "オレンジ", code: "C59", hex: "#f37821", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "オレンジイエロー", code: "C60", hex: "#f9bc1b", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "焼鉄色", code: "C61", hex: "#4d413a", type: PaintType.METALLIC, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "つや消しホワイト", code: "C62", hex: "#f0f0f0", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "matte" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "ピンク", code: "C63", hex: "#f0a2b6", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "RLM04 イエロー", code: "C64", hex: "#f7b731", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "インディブルー", code: "C65", hex: "#007ec5", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "RLM71 ダークグリーン", code: "C66", hex: "#4a4f3a", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "semi-gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "パープル", code: "C67", hex: "#8f4d9d", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "モンザレッド", code: "C68", hex: "#d8242a", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "RLM78 ライトブルー", code: "C69", hex: "#7b90a3", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "semi-gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "RLM80 オリーブグリーン", code: "C70", hex: "#6e6a39", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "semi-gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "ミッドナイトブルー", code: "C71", hex: "#222c3c", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "ダークグリーン", code: "C72", hex: "#3b483e", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "エアクラフトグレー", code: "C73", hex: "#a4a8aa", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "オリーブグリーン", code: "C74", hex: "#6c6a48", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "ダークシーグレー", code: "C75", hex: "#5a6468", type: PaintType.METALLIC, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "コバルトブルー", code: "C76", hex: "#0047ab", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "メタリックブルー", code: "C77", hex: "#4b6f95", type: PaintType.METALLIC, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "メタリックレッド", code: "C78", hex: "#a63d41", type: PaintType.METALLIC, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "シャインレッド", code: "C79", hex: "#e60012", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "デイトナグリーン", code: "C80", hex: "#00876a", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "蛍光レッド", code: "C87", hex: "#ff3a21", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "蛍光グリーン", code: "C88", hex: "#00ff7f", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "蛍光イエロー", code: "C89", hex: "#ffff00", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "蛍光ピンク", code: "C90", hex: "#ff69b4", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "蛍光オレンジ", code: "C91", hex: "#ffa500", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "スモークグレー", code: "C92", hex: "#808080", type: PaintType.CLEAR, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "クリアーオレンジ", code: "C93", hex: "#f58220", type: PaintType.CLEAR, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "クリアーグリーン", code: "C94", hex: "#009e49", type: PaintType.CLEAR, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "クリアーブラウン", code: "C101", hex: "#8c592a", type: PaintType.CLEAR, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "G-キャラクターホワイト", code: "C107", hex: "#f2f2f2", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "G-キャラクターレッド", code: "C108", hex: "#e63644", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "G-キャラクターイエロー", code: "C109", hex: "#f6b42c", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "G-キャラクターブルー", code: "C110", hex: "#2c8fde", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "G-キャラクターフレッシュ(1)", code: "C111", hex: "#f8d3c1", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "G-キャラクターフレッシュ(2)", code: "C112", hex: "#f8c6b1", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "RLM65 ライトブルー", code: "C115", hex: "#8fb1bc", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "semi-gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "RLM76 ライトブルー", code: "C117", hex: "#c0cdd1", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "semi-gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "RLM79 サンディイエロー", code: "C119", hex: "#a4815a", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "semi-gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "RLM81 ブラウンバイオレット", code: "C120", hex: "#6a5c4d", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "semi-gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "RLM82 ライトグリーン", code: "C121", hex: "#7a8459", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "semi-gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "RLM83 ダークグリーン", code: "C122", hex: "#474a3a", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "semi-gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "コクピット色(三菱系)", code: "C124", hex: "#5a664f", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "semi-gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "カウリング色", code: "C125", hex: "#2e343b", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "semi-gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "コクピット色(中島系)", code: "C126", hex: "#4a594b", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "semi-gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "機体内部色", code: "C127", hex: "#9d9b7c", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "semi-gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "灰色(三菱系)", code: "C128", hex: "#bfb8a6", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "semi-gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "濃緑色(三菱系)", code: "C129", hex: "#3a443a", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "semi-gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "濃緑色(中島系)", code: "C130", hex: "#41483f", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "semi-gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "あずき色", code: "C131", hex: "#8e4a4d", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "semi-gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "ダークグリーンWWII", code: "C132", hex: "#575d4e", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "semi-gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "赤褐色", code: "C136", hex: "#b05749", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "matte" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "タイヤブラック", code: "C137", hex: "#3f3f3f", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "matte" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "フラットベース(なめらか)", code: "C189", hex: "#ffffff", type: PaintType.CLEAR, paintSystem: PaintSystem.LACQUER, finish: "matte" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "オリーブドラブFS34087", code: "C304", hex: "#5a5647", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "semi-gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "グレーFS36118", code: "C305", hex: "#5b6063", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "semi-gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "グレーFS36231", code: "C306", hex: "#7a8286", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "semi-gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "グレーFS36320", code: "C307", hex: "#9da3a6", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "semi-gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "グレーFS36375", code: "C308", hex: "#c5c8c9", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "semi-gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "ダークシーグレー", code: "C331", hex: "#4f5a60", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "semi-gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "エクストラダークシーグレー", code: "C333", hex: "#5f6870", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "semi-gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "ミディアムシーグレー", code: "C335", hex: "#939ba0", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "semi-gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "ライトエアクラフトグレー", code: "C337", hex: "#c5c9c8", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "semi-gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "ダックエッググリーン", code: "C364", hex: "#adc2a9", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "semi-gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "RLM76 ライトブルー", code: "C368", hex: "#c0cdd1", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "semi-gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "ダークイエロー", code: "C512", hex: "#a98d54", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "semi-gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "ブラックグレー", code: "C513", hex: "#414342", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "semi-gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "ジャーマングレー(ドゥンケルグラウ)", code: "C514", hex: "#4b4f53", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "semi-gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "タン（ロシア）", code: "C517", hex: "#c3a985", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "semi-gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "ロシアングreen（１）", code: "C518", hex: "#5c604f", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "semi-gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "ブルー（ロシア）", code: "C519", hex: "#748ca0", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "semi-gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "RLM79 サンディブラウン", code: "C524", hex: "#9a7c55", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "semi-gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "ウイノーブラック", code: "C181", hex: "#1c1c1c", type: PaintType.NORMAL, paintSystem: PaintSystem.LACQUER, finish: "semi-gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "スーパークリアー つや消し", code: "C182", hex: "#ffffff", type: PaintType.CLEAR, paintSystem: PaintSystem.LACQUER, finish: "matte" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "スーパークリアー 光沢", code: "C184", hex: "#ffffff", type: PaintType.CLEAR, paintSystem: PaintSystem.LACQUER, finish: "gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "スーパークリアー 半光沢", code: "C188", hex: "#ffffff", type: PaintType.CLEAR, paintSystem: PaintSystem.LACQUER, finish: "semi-gloss" },
  { brand: Brand.CREOS, series: "Mr.カラー", name: "フラットベース", code: "C189", hex: "#ffffff", type: PaintType.CLEAR, paintSystem: PaintSystem.LACQUER, finish: "matte" },
];
